services:
  backend:
    build: .
    container_name: club_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always
    command: npm run dev

  mariadb:
    image: mariadb:11
    container_name: club_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: club_deportivo
      MYSQL_USER: club_user
      MYSQL_PASSWORD: club_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: